version: "3.7"
services:
  app:
    build: ./
    restart: always
    image: app
    ports:
      - 8089:8089
    networks:
      - mynetwork
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/kaddem_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    networks:
      - mynetwork
    environment:
      - MYSQL_DATABASE=kaddem_db
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=

networks:
  mynetwork:
    driver: bridge